// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database.types';

const SUPABASE_URL = "https://yidhyayqmnxeruzjylud.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZGh5YXlxbW54ZXJ1emp5bHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDE4ODUsImV4cCI6MjA1OTYxNzg4NX0.LyinElGE12H7FtX5LgEJ5Qb_AxCxxsrROKMch2rp2cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
